version: '3.8'

services:
  engine_supabase:
    container_name: engine_supabase
    build:
      context: .
      dockerfile: ./.docker/engine/Dockerfile
    networks:
      engine-net:
        aliases:
          - engine-supabase
      supabase_default:
        aliases:
          - engine-supabase
    ports:
      - "3001:3001"
    restart: on-failure
    healthcheck:
      test: "exit 0"
  server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.engine/nginx/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
    networks:
      engine-net:
        aliases:
          - engine-server
      supabase_default:
        aliases:
          - engine-server
  server-cert:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.engine/nginx_cert/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
    networks:
      engine-net:
        aliases:
          - engine-server-cert
  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - certs_www_volume:/var/www/certbot/:rw
      - certs_conf_volume:/etc/letsencrypt/:rw

volumes:
  certs_www_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.engine/certbot/www/
  certs_conf_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.engine/certbot/conf/

networks:
  engine-net:
    name: engine-net
  supabase_default:
    external: true
